name: Master
on: 
  push:
      branches:
        - main
env:
  HUGO_VERSION: '0.92.2'
  AZURE_CLI_VERSION: '2.33.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.PAT_TOKEN }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: '#{' # optional, default is #{
        tokenSuffix: '}#' # optional, default is }#
        files: '["config.toml"]'
      env:
        hostname: 'https://azurethamesvalleyprod.azureedge.net/'
    - name: Build
      run: hugo --minify    
    - name: Upload website as Artifact
      uses: actions/upload-artifact@v1
      with:
        name: website
        path: public
  publish:    
    environment:
      name: production.azure
    permissions:
          id-token: write
          contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: Download website changes
      uses: actions/download-artifact@v1
      with:
        name: website
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZURE_CLI_VERSION }}
        inlineScript: |
          az storage blob upload-batch --account-name azurethamesvalleyprod  -d '$web' -s website --auth-mode login
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZURE_CLI_VERSION }}
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "azurethamesvalley" --name "azurethamesvalleyprod" --resource-group "azurethamesvalley"